FROM node:16 AS build-stage
WORKDIR /usr/src/app

COPY . .

RUN npm ci

ENV CI=true


FROM build-stage as production-stage


RUN npm run build

FROM nginx:1.20-alpine
COPY --from=production-stage /usr/src/app/build /usr/share/nginx/html
